import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/adminpanel">AdminPanel</Link>
        </li>
        <li>
          <Link to="/mymember">MyMember</Link>
        </li>
        <li>
          <Link to="/allcars">AllCars</Link>
        </li>
        <li>
          <Link to="/supporthelp">SupportHelp</Link>
        </li>
        <li>
          <Link to="/settingprofile">SettingProfile</Link>
        </li>
        <li>
          <Link to="/settingeditprofile">SettingEditProfile</Link>
        </li>
        <li>
          <Link to="/settingprivacypolicy">SettingPrivacyPolicy</Link>
        </li>
        <li>
          <Link to="/settingtermscondition">SettingTermsCondition</Link>
        </li>
        <li>
          <Link to="/adminpanelone">AdminPanelOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
